### ISSUE TITLE
Lecture 8. Discrete Systems

### ISSUE THREAD

**Issue by annwhoorma** [SergeiSa/Linear-Control-Slides-Spring-2020#16]
Lecture starts with considering _autonomous system_ (which, as I understood, means that u(t) = 0). Slide 3:
![image](https://user-images.githubusercontent.com/34862867/79204493-4db87980-7e45-11ea-8ab4-96df96626b23.png)
Then we rewrtite the original equation in the following form. Slide 5:
![image](https://user-images.githubusercontent.com/34862867/79204579-7771a080-7e45-11ea-86d5-39a5d4787557.png)
And then we want to see if we can do the same with the system which u(t) != 0. But we do not mention that it is nonautonomous. Slide 6:
![image](https://user-images.githubusercontent.com/34862867/79204661-940dd880-7e45-11ea-9be8-eb25d3e909e8.png)

For us this material is very new and when we read we pick each word that might make something unclear. And here, for example, it's not clear for me why we need to state _explicitly_ that the first one is autonomous but we don't mention that the second one is nonautonomous. It seems to be not big of a deal but _it is frustrating_. It makes us doubt our knowledge and understanding, like "why here we say it but here we don't? does it even matter?"

My suggestion: when we look at different systems and want to compare them or derive some formulas, these systems should be described equally well to let us build our knowledge layer by layer

**Comment by SergeiSa** [comment]
The reason I mentioned that the first one is autonomous is because the implicit formula derivation requires this property. 

I will think about this question, thank you!

**Comment by SergeiSa** [comment]
Fixed!
