### ISSUE TITLE
Lecture 8. Slide 7

### ISSUE THREAD

**Issue by annwhoorma** [SergeiSa/Linear-Control-Slides-Spring-2020#18]
I suggest to add a space or some separator between these two equalities. As it is now, it looks like _B-dash_ is multiplied by the expession in parentheses
![image](https://user-images.githubusercontent.com/34862867/79212162-e227d980-7e4f-11ea-9821-a38ffe40536a.png)

**Comment by SergeiSa** [comment]
Sure =) You could just do it, it is \; in latex if I remember right

**Comment by SergeiSa** [comment]
Fixed!

**Comment by annwhoorma** [comment]
If you are okay with students modifying the slides, then next time I'll do it instead of opening an issue :)
Thank you!

**Comment by SergeiSa** [comment]
That is why they are on github, so everyone can contribute!
