### ISSUE TITLE
Lecture on Noise, Information, Observation (9th one)

### ISSUE THREAD

**Issue by pollytur** [SergeiSa/Linear-Control-Slides-Spring-2020#27]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/49938348/82435504-0f922380-9a9d-11ea-9de5-ee03ff0a582b.png">

Not really a mistake, but a misprint - 'thereforE' and lack of commas around this word

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/49938348/82436651-d6f34980-9a9e-11ea-8f45-ef8a7dd71294.png">

Here seems like the highlighted part should be "x dot hat"

Hope this will help)

**Comment by SergeiSa** [comment]
Fixed it! Thank you!
